# -*- coding: utf-8 -*-
"""calculadoraBrisa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SvmMYh8mc4FQp-46k0YOlGH0zZX9ay12
"""

print("\n******************* Python Calculator *******************")

#Função Soma
def soma(x,y):
  return x + y

#Função Subtração
def sub(x,y): 
  return x - y 

#Função Multiplicação
def mult(x,y):
  return x * y

#Função Divisão
def div(x,y):
  return x / y  

print('\nEscolha um número para a operação desejada: \n') 
print('1 - Soma') 
print('2 - Subtração')
print('3 - Multiplicação') 
print('4 - Divisão ')

operaçao = input('\nDigite sua opção 1/2/3/4: ')

num1 = float(input('\nDigite o primeiro número: '))
num2 = float(input('\nDigite o segundo número: '))

if operaçao == '1': 
  print('\n')
  print(num1, '+' ,num2, '=', round(soma(num1,num2),2))
  print('\n')

elif operaçao == '2': 
  print('\n')
  print(num1, '-' ,num2, '=', round(sub(num1,num2),2))
  print('\n')

elif operaçao == '3': 
  print('\n')
  print(num1, '*' ,num2, '=', round(mult(num1,num2),2))
  print('\n')

elif operaçao == '4': 
  print('\n')
  print(num1, '/' ,num2, '=', round(div(num1,num2),2))
  print('\n')

else:
  print('\nEntrada inválida! Escolha um opção entre 1 e 4')